
import java.awt.Cursor;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaEditarInfoLivro extends javax.swing.JFrame {

    private String titulo, autor, genero, sinopse;
    private int id_livro = 1;
    private UsuarioDAO livro = new UsuarioDAO();
    private CopiarImagem capa = new CopiarImagem();

    /**
     * Creates new form TelaEditarInfoLivro
     */
    public TelaEditarInfoLivro() {
        initComponents();
        InfoLivro(id_livro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JTextField();
        NotaLivro = new javax.swing.JComboBox<>();
        Autor = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        Sinopse = new javax.swing.JTextField();
        Caminho = new javax.swing.JTextField();
        BotVoltar = new javax.swing.JButton();
        BotEditarLivro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(93, 172, 156));
        Titulo.setBorder(null);
        Titulo.setOpaque(false);
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 222, 300, 20));

        NotaLivro.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        NotaLivro.setForeground(new java.awt.Color(93, 172, 156));
        NotaLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        NotaLivro.setToolTipText("");
        NotaLivro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NotaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaLivroActionPerformed(evt);
            }
        });
        getContentPane().add(NotaLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 222, 70, 20));

        Autor.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Autor.setForeground(new java.awt.Color(93, 172, 156));
        Autor.setBorder(null);
        Autor.setOpaque(false);
        Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorActionPerformed(evt);
            }
        });
        getContentPane().add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 268, 610, 20));

        Genero.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Genero.setForeground(new java.awt.Color(93, 172, 156));
        Genero.setBorder(null);
        Genero.setOpaque(false);
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });
        getContentPane().add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 310, 610, 20));

        Sinopse.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Sinopse.setForeground(new java.awt.Color(93, 172, 156));
        Sinopse.setBorder(null);
        Sinopse.setOpaque(false);
        Sinopse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinopseActionPerformed(evt);
            }
        });
        getContentPane().add(Sinopse, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 356, 610, 20));

        Caminho.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Caminho.setForeground(new java.awt.Color(93, 172, 156));
        Caminho.setBorder(null);
        Caminho.setOpaque(false);
        Caminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaminhoActionPerformed(evt);
            }
        });
        getContentPane().add(Caminho, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 405, 602, 20));

        BotVoltar.setBorder(null);
        BotVoltar.setContentAreaFilled(false);
        getContentPane().add(BotVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 105, 40));

        BotEditarLivro.setBorder(null);
        BotEditarLivro.setContentAreaFilled(false);
        BotEditarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotEditarLivroMouseEntered(evt);
            }
        });
        BotEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEditarLivroActionPerformed(evt);
            }
        });
        getContentPane().add(BotEditarLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 458, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaEditarInfoLivro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void InfoLivro(int id) {
        titulo = livro.obterNomeLivro(id);
        autor = livro.obterAutorLivro(id);
        genero = livro.obterGeneroLivro(id);
        sinopse = livro.obterSinopseLivro(id);
        id_livro = id;

        Titulo.setText(titulo);
        Autor.setText(autor);
        Genero.setText(genero);
        Sinopse.setText(sinopse);
        NotaLivro.setSelectedIndex(livro.obterNotaLivro(id));
    }


    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void NotaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaLivroActionPerformed

    private void SinopseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinopseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SinopseActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    private void AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorActionPerformed

    private void CaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaminhoActionPerformed

    private void BotEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEditarLivroActionPerformed
        // TODO add your handling code here:
        if (Titulo.getText() != null && Autor.getText() != null && Genero.getText() != null && Sinopse.getText() != null) {
            String nome_antigo;
            nome_antigo = livro.obterNomeLivro(id_livro);
            livro.atualizarInfo(id_livro, Titulo.getText(), Autor.getText(), Genero.getText(), Sinopse.getText(), NotaLivro.getSelectedIndex());
            capa.renomearArquivo("C:\\Users\\João\\Documents\\NetBeansProjects\\Telas\\src\\CapaLivros\\" + nome_antigo + ".jpg", Titulo.getText() + ".jpg");
            if (Caminho.getText() != null) {
                capa.CopiarImagem(Caminho.getText(), Titulo.getText());
            }
            JOptionPane.showMessageDialog(null, "Edição bem-sucedida");
            new TelaGerCatalogo().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Você não pode deixar nenhum campo vazio, exceto o Caminho do arquivo.");
        }
    }//GEN-LAST:event_BotEditarLivroActionPerformed

    private void BotEditarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEditarLivroMouseEntered
        // TODO add your handling code here:
        BotEditarLivro.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotEditarLivroMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autor;
    private javax.swing.JButton BotEditarLivro;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JTextField Caminho;
    private javax.swing.JTextField Genero;
    private javax.swing.JComboBox<String> NotaLivro;
    private javax.swing.JTextField Sinopse;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
