
import java.awt.Cursor;
import java.util.Vector;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaAdcExemplar extends javax.swing.JFrame {

    private UsuarioDAO livros = new UsuarioDAO();
    private String trecho;

    /**
     * Creates new form TelaAdcExemplar
     */
    public TelaAdcExemplar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotAdc = new javax.swing.JButton();
        BotVoltar = new javax.swing.JButton();
        Quant = new javax.swing.JTextField();
        LivroSelecionado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotAdc.setBorder(null);
        BotAdc.setContentAreaFilled(false);
        BotAdc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotAdcMouseEntered(evt);
            }
        });
        BotAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAdcActionPerformed(evt);
            }
        });
        getContentPane().add(BotAdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 115, 40));

        BotVoltar.setBorder(null);
        BotVoltar.setContentAreaFilled(false);
        BotVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotVoltarMouseEntered(evt);
            }
        });
        BotVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 420, 115, 40));

        Quant.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Quant.setForeground(new java.awt.Color(93, 172, 156));
        Quant.setBorder(null);
        Quant.setOpaque(false);
        Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantActionPerformed(evt);
            }
        });
        getContentPane().add(Quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 266, 500, 19));

        LivroSelecionado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LivroSelecionado.setForeground(new java.awt.Color(93, 172, 156));
        LivroSelecionado.setBorder(null);
        LivroSelecionado.setOpaque(false);
        LivroSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivroSelecionadoActionPerformed(evt);
            }
        });
        getContentPane().add(LivroSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 229, 490, 20));
        LivroSelecionado.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<>(livros.obterNomeLivros())));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaAdcExemplar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LivroSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivroSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LivroSelecionadoActionPerformed

    private void QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantActionPerformed

    private void BotAdcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAdcMouseEntered
        // TODO add your handling code here:
        BotAdc.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotAdcMouseEntered

    private void BotAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAdcActionPerformed
        // TODO add your handling code here:
        int inicio = ((String) LivroSelecionado.getSelectedItem()).indexOf(": ");
        int fim = ((String) LivroSelecionado.getSelectedItem()).indexOf(" -");

        if (inicio != -1 && fim != -1 && inicio < fim) {
            trecho = ((String) LivroSelecionado.getSelectedItem()).substring(inicio + 1, fim).trim();
            System.out.println("Trecho extraído: " + trecho);
        }
        Integer id = Integer.parseInt(trecho);
        livros.inserirExemplar(Integer.parseInt(Quant.getText()), id);
    }//GEN-LAST:event_BotAdcActionPerformed

    private void BotVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotVoltarMouseEntered
        // TODO add your handling code here:
        BotVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotVoltarMouseEntered

    private void BotVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltarActionPerformed
        // TODO add your handling code here:
        new TelaGerCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAdc;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JComboBox<String> LivroSelecionado;
    private javax.swing.JTextField Quant;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
