
import java.awt.Cursor;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaRealizarEmp extends javax.swing.JFrame {

    private String titulo, autor, genero, email, responsavel;
    private UsuarioDAO livro = new UsuarioDAO();
    private int id;

    /**
     * Creates new form TelaRealizarEmp
     */
    public TelaRealizarEmp(int id) {
        initComponents();
        this.id = id;
        mostrarInfo(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botVoltar = new javax.swing.JButton();
        BotEmprestimo = new javax.swing.JButton();
        Autor = new javax.swing.JLabel();
        Genero = new javax.swing.JLabel();
        Responsavel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Dt_Emp = new javax.swing.JLabel();
        Dt_Dev = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botVoltar.setContentAreaFilled(false);
        botVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botVoltarMouseEntered(evt);
            }
        });
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 494, 116, 40));

        BotEmprestimo.setContentAreaFilled(false);
        BotEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotEmprestimoMouseEntered(evt);
            }
        });
        BotEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(BotEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 494, 116, 40));

        Autor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Autor.setForeground(new java.awt.Color(93, 172, 156));
        getContentPane().add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 213, 612, 20));

        Genero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Genero.setForeground(new java.awt.Color(93, 172, 156));
        getContentPane().add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 256, 612, 20));

        Responsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Responsavel.setForeground(new java.awt.Color(93, 172, 156));
        getContentPane().add(Responsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 298, 612, 20));

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(93, 172, 156));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 344, 612, 20));

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(93, 172, 156));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 164, 612, 25));

        Dt_Emp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dt_Emp.setForeground(new java.awt.Color(93, 172, 156));
        getContentPane().add(Dt_Emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 390, 612, 20));

        Dt_Dev.setBorder(null);
        Dt_Dev.setForeground(new java.awt.Color(93, 172, 156));
        try {
            Dt_Dev.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Dt_Dev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Dt_Dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dt_DevActionPerformed(evt);
            }
        });
        getContentPane().add(Dt_Dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 440, 612, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaRealizarEmp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarInfo(int id) {
        titulo = livro.obterNomeLivro(id);
        autor = livro.obterAutorLivro(id);
        genero = livro.obterGeneroLivro(id);
        responsavel = livro.obterNomeAtual();
        LocalDate dataAtual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        email = livro.obterEmailAtual();

        Titulo.setText(titulo);
        Autor.setText(autor);
        Genero.setText(genero);
        Responsavel.setText(responsavel);
        Dt_Emp.setText(dataAtual.format(formato));
        Email.setText(email);

    }
    private void botVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botVoltarMouseEntered
        // TODO add your handling code here:
        botVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botVoltarMouseEntered

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botVoltarActionPerformed

    private void BotEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEmprestimoMouseEntered
        // TODO add your handling code here:
        BotEmprestimo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotEmprestimoMouseEntered

    private void BotEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEmprestimoActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataTexto = Dt_Dev.getText().trim();

        if (dataTexto.isEmpty() || dataTexto.contains("_")) {
            JOptionPane.showMessageDialog(this, "Por favor, insira uma data de devolução válida.");
            return;
        }
        LocalDate Dt_Devolucao = LocalDate.parse(dataTexto, formato);
        LocalDate Dt_Emprestimo = LocalDate.now();

        String retorno = livro.inserirEmprestimo(id, livro.obterIDAtual(), Dt_Emprestimo, Dt_Devolucao);
        if (retorno.equalsIgnoreCase("Emprestimo realizado com sucesso!")) {
            new TelaEmpSucesso().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, retorno);
        }
    }//GEN-LAST:event_BotEmprestimoActionPerformed

    private void Dt_DevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dt_DevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dt_DevActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JButton BotEmprestimo;
    private javax.swing.JFormattedTextField Dt_Dev;
    private javax.swing.JLabel Dt_Emp;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Genero;
    private javax.swing.JLabel Responsavel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
