
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaCatalogo extends javax.swing.JFrame {

    UsuarioDAO verificarAdm = new UsuarioDAO();
    UsuarioDAO livros = new UsuarioDAO();
    ArrayList<Integer> ids_livro = new ArrayList<Integer>();
    int i = 0;

    /**
     * Creates new form Catalogo
     */
    public TelaCatalogo() {
        ids_livro = livros.obterIdLivros();
        System.out.println(ids_livro);
        initComponents();
        atualizarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotCatalogo = new javax.swing.JButton();
        BotMinhaConta = new javax.swing.JButton();
        BotSair = new javax.swing.JButton();
        BotInicio = new javax.swing.JButton();
        BotLivro1 = new javax.swing.JButton();
        BotLivro2 = new javax.swing.JButton();
        BotLivro3 = new javax.swing.JButton();
        BotLivro4 = new javax.swing.JButton();
        BotLivro5 = new javax.swing.JButton();
        BotLivro6 = new javax.swing.JButton();
        NomeL1 = new javax.swing.JLabel();
        NomeL2 = new javax.swing.JLabel();
        NomeL3 = new javax.swing.JLabel();
        NomeL4 = new javax.swing.JLabel();
        NomeL5 = new javax.swing.JLabel();
        NomeL6 = new javax.swing.JLabel();
        livro1 = new javax.swing.JLabel();
        livro2 = new javax.swing.JLabel();
        livro3 = new javax.swing.JLabel();
        livro4 = new javax.swing.JLabel();
        livro5 = new javax.swing.JLabel();
        livro6 = new javax.swing.JLabel();
        BotGerCatalogo = new javax.swing.JButton();
        ImgGerCatalogo = new javax.swing.JLabel();
        BotDir = new javax.swing.JButton();
        BotEsq = new javax.swing.JButton();
        SetaDir = new javax.swing.JLabel();
        SetaEsq = new javax.swing.JLabel();
        Estrelas5L1 = new javax.swing.JLabel();
        Estrelas4L1 = new javax.swing.JLabel();
        Estrelas3L1 = new javax.swing.JLabel();
        Estrelas2L1 = new javax.swing.JLabel();
        Estrelas1L1 = new javax.swing.JLabel();
        Estrelas0L1 = new javax.swing.JLabel();
        AutorL1 = new javax.swing.JLabel();
        GeneroL1 = new javax.swing.JLabel();
        Estrelas5L2 = new javax.swing.JLabel();
        Estrelas4L2 = new javax.swing.JLabel();
        Estrelas3L2 = new javax.swing.JLabel();
        Estrelas2L2 = new javax.swing.JLabel();
        Estrelas1L2 = new javax.swing.JLabel();
        Estrelas0L2 = new javax.swing.JLabel();
        AutorL2 = new javax.swing.JLabel();
        GeneroL2 = new javax.swing.JLabel();
        Estrelas5L3 = new javax.swing.JLabel();
        Estrelas4L3 = new javax.swing.JLabel();
        Estrelas3L3 = new javax.swing.JLabel();
        Estrelas2L3 = new javax.swing.JLabel();
        Estrelas1L3 = new javax.swing.JLabel();
        Estrelas0L3 = new javax.swing.JLabel();
        AutorL3 = new javax.swing.JLabel();
        GeneroL3 = new javax.swing.JLabel();
        Estrelas5L4 = new javax.swing.JLabel();
        Estrelas4L4 = new javax.swing.JLabel();
        Estrelas3L4 = new javax.swing.JLabel();
        Estrelas2L4 = new javax.swing.JLabel();
        Estrelas1L4 = new javax.swing.JLabel();
        Estrelas0L4 = new javax.swing.JLabel();
        AutorL4 = new javax.swing.JLabel();
        GeneroL4 = new javax.swing.JLabel();
        Estrelas5L5 = new javax.swing.JLabel();
        Estrelas4L5 = new javax.swing.JLabel();
        Estrelas3L5 = new javax.swing.JLabel();
        Estrelas2L5 = new javax.swing.JLabel();
        Estrelas1L5 = new javax.swing.JLabel();
        Estrelas0L5 = new javax.swing.JLabel();
        AutorL5 = new javax.swing.JLabel();
        GeneroL5 = new javax.swing.JLabel();
        Estrelas5L6 = new javax.swing.JLabel();
        Estrelas4L6 = new javax.swing.JLabel();
        Estrelas3L6 = new javax.swing.JLabel();
        Estrelas2L6 = new javax.swing.JLabel();
        Estrelas1L6 = new javax.swing.JLabel();
        Estrelas0L6 = new javax.swing.JLabel();
        AutorL6 = new javax.swing.JLabel();
        GeneroL6 = new javax.swing.JLabel();
        Pesquisa = new javax.swing.JTextField();
        BotPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotCatalogo.setBorder(null);
        BotCatalogo.setContentAreaFilled(false);
        BotCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotCatalogoMouseEntered(evt);
            }
        });
        BotCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 190, 38));

        BotMinhaConta.setBorder(null);
        BotMinhaConta.setContentAreaFilled(false);
        BotMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotMinhaContaMouseEntered(evt);
            }
        });
        BotMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMinhaContaActionPerformed(evt);
            }
        });
        getContentPane().add(BotMinhaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 192, 35));

        BotSair.setBorder(null);
        BotSair.setContentAreaFilled(false);
        BotSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotSairMouseEntered(evt);
            }
        });
        BotSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 190, 30));

        BotInicio.setBorder(null);
        BotInicio.setContentAreaFilled(false);
        BotInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicioMouseEntered(evt);
            }
        });
        BotInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 190, 38));

        BotLivro1.setBorder(null);
        BotLivro1.setContentAreaFilled(false);
        BotLivro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro1MouseEntered(evt);
            }
        });
        BotLivro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 110, 83, 125));

        BotLivro2.setBorder(null);
        BotLivro2.setContentAreaFilled(false);
        BotLivro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro2MouseEntered(evt);
            }
        });
        BotLivro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 83, 125));

        BotLivro3.setBorder(null);
        BotLivro3.setContentAreaFilled(false);
        BotLivro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro3MouseEntered(evt);
            }
        });
        BotLivro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 110, 83, 125));

        BotLivro4.setBorder(null);
        BotLivro4.setContentAreaFilled(false);
        BotLivro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro4MouseEntered(evt);
            }
        });
        BotLivro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro4ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 350, 83, 125));

        BotLivro5.setBorder(null);
        BotLivro5.setContentAreaFilled(false);
        BotLivro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro5MouseEntered(evt);
            }
        });
        BotLivro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro5ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 83, 125));

        BotLivro6.setBorder(null);
        BotLivro6.setContentAreaFilled(false);
        BotLivro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro6MouseEntered(evt);
            }
        });
        BotLivro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro6ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 350, 83, 125));

        NomeL1.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL1.setForeground(new java.awt.Color(45, 123, 109));
        NomeL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 258, 184, 20));
        if(1+i<=ids_livro.size()){
            NomeL1.setText(livros.obterNomeLivro(ids_livro.get(1+i-1)));
        }

        NomeL2.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL2.setForeground(new java.awt.Color(45, 123, 109));
        NomeL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 258, 184, 20));
        if(2+i<=ids_livro.size()){
            NomeL2.setText(livros.obterNomeLivro(ids_livro.get(2+i-1)));
        }

        NomeL3.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL3.setForeground(new java.awt.Color(45, 123, 109));
        NomeL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 258, 184, 20));
        if(3+i<=ids_livro.size()){
            NomeL3.setText(livros.obterNomeLivro(ids_livro.get(3+i-1)));
        }

        NomeL4.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL4.setForeground(new java.awt.Color(45, 123, 109));
        NomeL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 498, 184, 20));
        if(4+i<=ids_livro.size()){
            NomeL4.setText(livros.obterNomeLivro(ids_livro.get(4+i-1)));
        }

        NomeL5.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL5.setForeground(new java.awt.Color(45, 123, 109));
        NomeL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 498, 184, 20));
        if(5+i<=ids_livro.size()){
            NomeL5.setText(livros.obterNomeLivro(ids_livro.get(5+i-1)));
        }

        NomeL6.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL6.setForeground(new java.awt.Color(45, 123, 109));
        NomeL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 498, 184, 20));
        if(6+i<=ids_livro.size()){
            NomeL6.setText(livros.obterNomeLivro(ids_livro.get(6+i-1)));
        }
        getContentPane().add(livro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 110, 83, 125));
        if (!NomeL1.getText().equalsIgnoreCase("")){
            livro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL1.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 83, 125));
        if (!NomeL2.getText().equalsIgnoreCase("")){
            livro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL2.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 110, 83, 125));
        if (!NomeL3.getText().equalsIgnoreCase("")){
            livro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL3.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 350, 83, 125));
        if (!NomeL4.getText().equalsIgnoreCase("")){
            livro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL4.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 83, 125));
        if (!NomeL5.getText().equalsIgnoreCase("")){
            livro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL5.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 350, 83, 125));
        if (!NomeL6.getText().equalsIgnoreCase("")){
            livro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL6.getText()+".jpg"))); // NOI18N
        }

        BotGerCatalogo.setBorder(null);
        BotGerCatalogo.setContentAreaFilled(false);
        BotGerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotGerCatalogoMouseEntered(evt);
            }
        });
        BotGerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            BotGerCatalogo.setEnabled(true);
        } else {
            BotGerCatalogo.setEnabled(false);
        }

        ImgGerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/BotGerenciar.png"))); // NOI18N
        getContentPane().add(ImgGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            ImgGerCatalogo.setVisible(true);
        } else {
            ImgGerCatalogo.setVisible(false);
        }

        BotDir.setBorder(null);
        BotDir.setBorderPainted(false);
        BotDir.setContentAreaFilled(false);
        BotDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotDirMouseEntered(evt);
            }
        });
        BotDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDirActionPerformed(evt);
            }
        });
        getContentPane().add(BotDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 18, 30));
        if(i+6>ids_livro.size()){
            BotDir.setEnabled(false);
        }

        BotEsq.setBorder(null);
        BotEsq.setBorderPainted(false);
        BotEsq.setContentAreaFilled(false);
        BotEsq.setEnabled(false);
        BotEsq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotEsqMouseEntered(evt);
            }
        });
        BotEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEsqActionPerformed(evt);
            }
        });
        getContentPane().add(BotEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 310, 18, 30));
        if(i>=6){
            BotEsq.setEnabled(true);
        }

        SetaDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/SetaDir.png"))); // NOI18N
        getContentPane().add(SetaDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 18, 30));
        if(i+6>ids_livro.size()){
            SetaDir.setVisible(false);
        }

        SetaEsq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/SetaEsq.png"))); // NOI18N
        getContentPane().add(SetaEsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 310, 18, 30));
        SetaEsq.setVisible(false);
        if(i>=6){
            SetaEsq.setVisible(true);
        }

        Estrelas5L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas5L1.setVisible(false);

        Estrelas4L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas4L1.setVisible(false);

        Estrelas3L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas3L1.setVisible(false);

        Estrelas2L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas2L1.setVisible(false);

        Estrelas1L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas1L1.setVisible(false);

        Estrelas0L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas0L1.setVisible(false);

        AutorL1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL1.setForeground(new java.awt.Color(93, 172, 156));
        AutorL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 273, 184, 20));
        if(1+i<=ids_livro.size()){
            AutorL1.setText(livros.obterAutorLivro(ids_livro.get(1+i-1)));
        }

        GeneroL1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL1.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 288, 184, 20));
        if(1+i<=ids_livro.size()){
            GeneroL1.setText(livros.obterGeneroLivro(ids_livro.get(1+i-1)));
        }

        Estrelas5L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas5L2.setVisible(false);

        Estrelas4L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas4L2.setVisible(false);

        Estrelas3L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas3L2.setVisible(false);

        Estrelas2L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas2L2.setVisible(false);

        Estrelas1L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas1L2.setVisible(false);

        Estrelas0L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas0L2.setVisible(false);

        AutorL2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL2.setForeground(new java.awt.Color(93, 172, 156));
        AutorL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 273, 184, 20));
        if(2+i<=ids_livro.size()){
            AutorL2.setText(livros.obterAutorLivro(ids_livro.get(2+i-1)));
        }

        GeneroL2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL2.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 288, 184, 20));
        if(2+i<=ids_livro.size()){
            GeneroL2.setText(livros.obterGeneroLivro(ids_livro.get(2+i-1)));
        }

        Estrelas5L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas5L3.setVisible(false);

        Estrelas4L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas4L3.setVisible(false);

        Estrelas3L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas3L3.setVisible(false);

        Estrelas2L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas2L3.setVisible(false);

        Estrelas1L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas1L3.setVisible(false);

        Estrelas0L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas0L3.setVisible(false);

        AutorL3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL3.setForeground(new java.awt.Color(93, 172, 156));
        AutorL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 273, 184, 20));
        if(3+i<=ids_livro.size()){
            AutorL3.setText(livros.obterAutorLivro(ids_livro.get(3+i-1)));
        }

        GeneroL3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL3.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 288, 184, 20));
        if(3+i<=ids_livro.size()){
            GeneroL3.setText(livros.obterGeneroLivro(ids_livro.get(3+i-1)));
        }

        Estrelas5L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas5L4.setVisible(false);

        Estrelas4L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas4L4.setVisible(false);

        Estrelas3L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas3L4.setVisible(false);

        Estrelas2L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas2L4.setVisible(false);

        Estrelas1L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas1L4.setVisible(false);

        Estrelas0L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 480, 83, 18));
        Estrelas0L4.setVisible(false);

        AutorL4.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL4.setForeground(new java.awt.Color(93, 172, 156));
        AutorL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 512, 184, 20));
        if(4+i<=ids_livro.size()){
            AutorL4.setText(livros.obterAutorLivro(ids_livro.get(4+i-1)));
        }

        GeneroL4.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL4.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 527, 184, 20));
        if(4+i<=ids_livro.size()){
            GeneroL4.setText(livros.obterGeneroLivro(ids_livro.get(4+i-1)));
        }

        Estrelas5L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas5L5.setVisible(false);

        Estrelas4L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas4L5.setVisible(false);

        Estrelas3L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas3L5.setVisible(false);

        Estrelas2L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas2L5.setVisible(false);

        Estrelas1L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas1L5.setVisible(false);

        Estrelas0L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 480, 83, 18));
        Estrelas0L5.setVisible(false);

        AutorL5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL5.setForeground(new java.awt.Color(93, 172, 156));
        AutorL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 512, 184, 20));
        if(5+i<=ids_livro.size()){
            AutorL5.setText(livros.obterAutorLivro(ids_livro.get(5+i-1)));
        }

        GeneroL5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL5.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 527, 184, 20));
        if(5+i<=ids_livro.size()){
            GeneroL5.setText(livros.obterGeneroLivro(ids_livro.get(5+i-1)));
        }

        Estrelas5L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas5L6.setVisible(false);

        Estrelas4L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas4L6.setVisible(false);

        Estrelas3L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas3L6.setVisible(false);

        Estrelas2L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas2L6.setVisible(false);

        Estrelas1L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas1L6.setVisible(false);

        Estrelas0L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 480, 83, 18));
        Estrelas0L6.setVisible(false);

        AutorL6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL6.setForeground(new java.awt.Color(93, 172, 156));
        AutorL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 512, 184, 20));
        if(6+i<=ids_livro.size()){
            AutorL6.setText(livros.obterAutorLivro(ids_livro.get(6+i-1)));
        }

        GeneroL6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL6.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 527, 184, 20));
        if(6+i<=ids_livro.size()){
            GeneroL6.setText(livros.obterGeneroLivro(ids_livro.get(6+i-1)));
        }

        Pesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pesquisa.setForeground(new java.awt.Color(93, 172, 156));
        Pesquisa.setBorder(null);
        Pesquisa.setOpaque(false);
        Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 34, 266, 25));

        BotPesquisar.setContentAreaFilled(false);
        BotPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BotPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 34, 22, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaCatalogo.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarCatalogo() {
        if (1 + i <= ids_livro.size()) {
            NomeL1.setText(livros.obterNomeLivro(ids_livro.get(1 + i - 1)));
            livro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL1.getText() + ".jpg")));
            AutorL1.setText(livros.obterAutorLivro(ids_livro.get(1 + i - 1)));
            GeneroL1.setText(livros.obterGeneroLivro(ids_livro.get(1 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(1 + i - 1));
            Estrelas0L1.setVisible(nota == 0);
            Estrelas1L1.setVisible(nota == 1);
            Estrelas2L1.setVisible(nota == 2);
            Estrelas3L1.setVisible(nota == 3);
            Estrelas4L1.setVisible(nota == 4);
            Estrelas5L1.setVisible(nota == 5);
            BotLivro1.setEnabled(true);
        } else {
            Estrelas0L1.setVisible(false); 
            Estrelas1L1.setVisible(false); 
            Estrelas2L1.setVisible(false);
            Estrelas3L1.setVisible(false); 
            Estrelas4L1.setVisible(false); 
            Estrelas5L1.setVisible(false);
            NomeL1.setText("");
            livro1.setIcon(null);
            AutorL1.setText("");
            GeneroL1.setText("");
            BotLivro1.setEnabled(false);
        }

        if (2 + i <= ids_livro.size()) {
            NomeL2.setText(livros.obterNomeLivro(ids_livro.get(2 + i - 1)));
            livro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL2.getText() + ".jpg")));
            AutorL2.setText(livros.obterAutorLivro(ids_livro.get(2 + i - 1)));
            GeneroL2.setText(livros.obterGeneroLivro(ids_livro.get(2 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(2 + i - 1));
            Estrelas0L2.setVisible(nota == 0);
            Estrelas1L2.setVisible(nota == 1);
            Estrelas2L2.setVisible(nota == 2);
            Estrelas3L2.setVisible(nota == 3);
            Estrelas4L2.setVisible(nota == 4);
            Estrelas5L2.setVisible(nota == 5);
            BotLivro2.setEnabled(true);
        } else {
            Estrelas0L2.setVisible(false); 
            Estrelas1L2.setVisible(false); 
            Estrelas2L2.setVisible(false);
            Estrelas3L2.setVisible(false); 
            Estrelas4L2.setVisible(false); 
            Estrelas5L2.setVisible(false);
            NomeL2.setText("");
            livro2.setIcon(null);
            AutorL2.setText("");
            GeneroL2.setText("");
            BotLivro2.setEnabled(false);
        }

        if (3 + i <= ids_livro.size()) {
            NomeL3.setText(livros.obterNomeLivro(ids_livro.get(3 + i - 1)));
            livro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL3.getText() + ".jpg")));
            AutorL3.setText(livros.obterAutorLivro(ids_livro.get(3 + i - 1)));
            GeneroL3.setText(livros.obterGeneroLivro(ids_livro.get(3 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(3 + i - 1));
            Estrelas0L3.setVisible(nota == 0);
            Estrelas1L3.setVisible(nota == 1);
            Estrelas2L3.setVisible(nota == 2);
            Estrelas3L3.setVisible(nota == 3);
            Estrelas4L3.setVisible(nota == 4);
            Estrelas5L3.setVisible(nota == 5);
            BotLivro3.setEnabled(true);
        } else {
            Estrelas0L3.setVisible(false); 
            Estrelas1L3.setVisible(false); 
            Estrelas2L3.setVisible(false);
            Estrelas3L3.setVisible(false); 
            Estrelas4L3.setVisible(false); 
            Estrelas5L3.setVisible(false);
            NomeL3.setText("");
            livro3.setIcon(null);
            AutorL3.setText("");
            GeneroL3.setText("");
            BotLivro3.setEnabled(false);
        }

        if (4 + i <= ids_livro.size()) {
            NomeL4.setText(livros.obterNomeLivro(ids_livro.get(4 + i - 1)));
            livro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL4.getText() + ".jpg")));
            AutorL4.setText(livros.obterAutorLivro(ids_livro.get(4 + i - 1)));
            GeneroL4.setText(livros.obterGeneroLivro(ids_livro.get(4 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(4 + i - 1));
            Estrelas0L4.setVisible(nota == 0);
            Estrelas1L4.setVisible(nota == 1);
            Estrelas2L4.setVisible(nota == 2);
            Estrelas3L4.setVisible(nota == 3);
            Estrelas4L4.setVisible(nota == 4);
            Estrelas5L4.setVisible(nota == 5);
            BotLivro4.setEnabled(true);
        } else {
            Estrelas0L4.setVisible(false); 
            Estrelas1L4.setVisible(false); 
            Estrelas2L4.setVisible(false);
            Estrelas3L4.setVisible(false); 
            Estrelas4L4.setVisible(false); 
            Estrelas5L4.setVisible(false);
            NomeL4.setText("");
            livro4.setIcon(null);
            AutorL4.setText("");
            GeneroL4.setText("");
            BotLivro4.setEnabled(false);
        }

        if (5 + i <= ids_livro.size()) {
            NomeL5.setText(livros.obterNomeLivro(ids_livro.get(5 + i - 1)));
            livro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL5.getText() + ".jpg")));
            AutorL5.setText(livros.obterAutorLivro(ids_livro.get(5 + i - 1)));
            GeneroL5.setText(livros.obterGeneroLivro(ids_livro.get(5 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(5 + i - 1));
            Estrelas0L5.setVisible(nota == 0);
            Estrelas1L5.setVisible(nota == 1);
            Estrelas2L5.setVisible(nota == 2);
            Estrelas3L5.setVisible(nota == 3);
            Estrelas4L5.setVisible(nota == 4);
            Estrelas5L5.setVisible(nota == 5);
            BotLivro5.setEnabled(true);
        } else {
            Estrelas0L5.setVisible(false); 
            Estrelas1L5.setVisible(false); 
            Estrelas2L5.setVisible(false);
            Estrelas3L5.setVisible(false); 
            Estrelas4L5.setVisible(false); 
            Estrelas5L5.setVisible(false);
            NomeL5.setText("");
            livro5.setIcon(null);
            AutorL5.setText("");
            GeneroL5.setText("");
            BotLivro5.setEnabled(false);
        }
        
        if (6 + i <= ids_livro.size()) {
            NomeL6.setText(livros.obterNomeLivro(ids_livro.get(6 + i - 1)));
            livro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL6.getText() + ".jpg")));
            AutorL6.setText(livros.obterAutorLivro(ids_livro.get(6 + i - 1)));
            GeneroL6.setText(livros.obterGeneroLivro(ids_livro.get(6 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(6 + i - 1));
            Estrelas0L6.setVisible(nota == 0);
            Estrelas1L6.setVisible(nota == 1);
            Estrelas2L6.setVisible(nota == 2);
            Estrelas3L6.setVisible(nota == 3);
            Estrelas4L6.setVisible(nota == 4);
            Estrelas5L6.setVisible(nota == 5);
            BotLivro6.setEnabled(true);
        } else {
            Estrelas0L6.setVisible(false); 
            Estrelas1L6.setVisible(false); 
            Estrelas2L6.setVisible(false);
            Estrelas3L6.setVisible(false); 
            Estrelas4L6.setVisible(false); 
            Estrelas5L6.setVisible(false);
            NomeL6.setText("");
            livro6.setIcon(null);
            AutorL6.setText("");
            GeneroL6.setText("");
            BotLivro6.setEnabled(false);
        }
        

        // Atualiza visibilidade dos botões de navegação 
        BotDir.setEnabled(i + 6 < ids_livro.size());
        SetaDir.setVisible(i + 6 < ids_livro.size());
        BotEsq.setEnabled(i >= 6);
        SetaEsq.setVisible(i >= 6);
    }

    private void BotCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotCatalogoMouseEntered
        // TODO add your handling code here:
        BotCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotCatalogoMouseEntered

    private void BotCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCatalogoActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotCatalogoActionPerformed

    private void BotMinhaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotMinhaContaMouseEntered
        // TODO add your handling code here:
        BotMinhaConta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotMinhaContaMouseEntered

    private void BotMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMinhaContaActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotMinhaContaActionPerformed

    private void BotSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSairMouseEntered
        // TODO add your handling code here:
        BotSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotSairMouseEntered

    private void BotSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSairActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Você está saindo!");
        setVisible(false);
        new TelaCadastro().setVisible(true);

    }//GEN-LAST:event_BotSairActionPerformed

    private void BotInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicioMouseEntered
        // TODO add your handling code here:
        BotInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicioMouseEntered

    private void BotInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicioActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicioActionPerformed

    private void BotGerCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotGerCatalogoMouseEntered
        // TODO add your handling code here:
        BotGerCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotGerCatalogoMouseEntered

    private void BotGerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerCatalogoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerCatalogo().setVisible(true);
    }//GEN-LAST:event_BotGerCatalogoActionPerformed

    private void BotDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDirActionPerformed
        // TODO add your handling code here:
        i = i + 6;
        atualizarCatalogo();
    }//GEN-LAST:event_BotDirActionPerformed

    private void BotDirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotDirMouseEntered
        // TODO add your handling code here:
        BotDir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotDirMouseEntered

    private void BotEsqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEsqMouseEntered
        // TODO add your handling code here:
        BotEsq.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotEsqMouseEntered

    private void BotEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEsqActionPerformed
        // TODO add your handling code here:
        i = i - 6;
        atualizarCatalogo();
    }//GEN-LAST:event_BotEsqActionPerformed

    private void BotLivro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro1MouseEntered
        BotLivro1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro1MouseEntered

    private void BotLivro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro1ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(1 + i - 1)).setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_BotLivro1ActionPerformed

    private void BotLivro2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro2MouseEntered
        // TODO add your handling code here:
        BotLivro2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro2MouseEntered

    private void BotLivro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro2ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(2 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro2ActionPerformed

    private void BotLivro3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro3MouseEntered
        // TODO add your handling code here:
        BotLivro3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro3MouseEntered

    private void BotLivro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro3ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(3 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro3ActionPerformed

    private void BotLivro4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro4MouseEntered
        // TODO add your handling code here:
        BotLivro4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro4MouseEntered

    private void BotLivro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro4ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(4 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro4ActionPerformed

    private void BotLivro5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro5MouseEntered
        // TODO add your handling code here:
        BotLivro5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro5MouseEntered

    private void BotLivro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro5ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(5 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro5ActionPerformed

    private void BotLivro6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro6MouseEntered
        // TODO add your handling code here:
        BotLivro6.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro6MouseEntered

    private void BotLivro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro6ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(6 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro6ActionPerformed

    private void PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void BotPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotPesquisarActionPerformed
        // TODO add your handling code here:
        ids_livro.removeAll(ids_livro);
        ids_livro = (livros.obterIdLivrosPesquisa(Pesquisa.getText()));
        atualizarCatalogo();
        
    }//GEN-LAST:event_BotPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorL1;
    private javax.swing.JLabel AutorL2;
    private javax.swing.JLabel AutorL3;
    private javax.swing.JLabel AutorL4;
    private javax.swing.JLabel AutorL5;
    private javax.swing.JLabel AutorL6;
    private javax.swing.JButton BotCatalogo;
    private javax.swing.JButton BotDir;
    private javax.swing.JButton BotEsq;
    private javax.swing.JButton BotGerCatalogo;
    private javax.swing.JButton BotInicio;
    private javax.swing.JButton BotLivro1;
    private javax.swing.JButton BotLivro2;
    private javax.swing.JButton BotLivro3;
    private javax.swing.JButton BotLivro4;
    private javax.swing.JButton BotLivro5;
    private javax.swing.JButton BotLivro6;
    private javax.swing.JButton BotMinhaConta;
    private javax.swing.JButton BotPesquisar;
    private javax.swing.JButton BotSair;
    private javax.swing.JLabel Estrelas0L1;
    private javax.swing.JLabel Estrelas0L2;
    private javax.swing.JLabel Estrelas0L3;
    private javax.swing.JLabel Estrelas0L4;
    private javax.swing.JLabel Estrelas0L5;
    private javax.swing.JLabel Estrelas0L6;
    private javax.swing.JLabel Estrelas1L1;
    private javax.swing.JLabel Estrelas1L2;
    private javax.swing.JLabel Estrelas1L3;
    private javax.swing.JLabel Estrelas1L4;
    private javax.swing.JLabel Estrelas1L5;
    private javax.swing.JLabel Estrelas1L6;
    private javax.swing.JLabel Estrelas2L1;
    private javax.swing.JLabel Estrelas2L2;
    private javax.swing.JLabel Estrelas2L3;
    private javax.swing.JLabel Estrelas2L4;
    private javax.swing.JLabel Estrelas2L5;
    private javax.swing.JLabel Estrelas2L6;
    private javax.swing.JLabel Estrelas3L1;
    private javax.swing.JLabel Estrelas3L2;
    private javax.swing.JLabel Estrelas3L3;
    private javax.swing.JLabel Estrelas3L4;
    private javax.swing.JLabel Estrelas3L5;
    private javax.swing.JLabel Estrelas3L6;
    private javax.swing.JLabel Estrelas4L1;
    private javax.swing.JLabel Estrelas4L2;
    private javax.swing.JLabel Estrelas4L3;
    private javax.swing.JLabel Estrelas4L4;
    private javax.swing.JLabel Estrelas4L5;
    private javax.swing.JLabel Estrelas4L6;
    private javax.swing.JLabel Estrelas5L1;
    private javax.swing.JLabel Estrelas5L2;
    private javax.swing.JLabel Estrelas5L3;
    private javax.swing.JLabel Estrelas5L4;
    private javax.swing.JLabel Estrelas5L5;
    private javax.swing.JLabel Estrelas5L6;
    private javax.swing.JLabel GeneroL1;
    private javax.swing.JLabel GeneroL2;
    private javax.swing.JLabel GeneroL3;
    private javax.swing.JLabel GeneroL4;
    private javax.swing.JLabel GeneroL5;
    private javax.swing.JLabel GeneroL6;
    private javax.swing.JLabel ImgGerCatalogo;
    private javax.swing.JLabel NomeL1;
    private javax.swing.JLabel NomeL2;
    private javax.swing.JLabel NomeL3;
    private javax.swing.JLabel NomeL4;
    private javax.swing.JLabel NomeL5;
    private javax.swing.JLabel NomeL6;
    private javax.swing.JTextField Pesquisa;
    private javax.swing.JLabel SetaDir;
    private javax.swing.JLabel SetaEsq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel livro1;
    private javax.swing.JLabel livro2;
    private javax.swing.JLabel livro3;
    private javax.swing.JLabel livro4;
    private javax.swing.JLabel livro5;
    private javax.swing.JLabel livro6;
    // End of variables declaration//GEN-END:variables
}
