
import java.awt.Cursor;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaGerCatalogo extends javax.swing.JFrame {
    
    UsuarioDAO quant = new UsuarioDAO();
    /**
     * Creates new form TelaGerCatalogo
     */
    public TelaGerCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotInicio = new javax.swing.JButton();
        BotRmvExemplar = new javax.swing.JButton();
        BotEditarInfo = new javax.swing.JButton();
        BotInicio1 = new javax.swing.JButton();
        BotAdcLivro = new javax.swing.JButton();
        BotRmvLivro = new javax.swing.JButton();
        BotAdcExemplar = new javax.swing.JButton();
        BotObterDados = new javax.swing.JButton();
        BotInicio2 = new javax.swing.JButton();
        BotInicio3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotInicio.setBorder(null);
        BotInicio.setContentAreaFilled(false);
        BotInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicioMouseEntered(evt);
            }
        });
        BotInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 190, 38));

        BotRmvExemplar.setBorder(null);
        BotRmvExemplar.setContentAreaFilled(false);
        BotRmvExemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotRmvExemplarMouseEntered(evt);
            }
        });
        BotRmvExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRmvExemplarActionPerformed(evt);
            }
        });
        getContentPane().add(BotRmvExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 308, 556, 46));

        BotEditarInfo.setBorder(null);
        BotEditarInfo.setContentAreaFilled(false);
        BotEditarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotEditarInfoMouseEntered(evt);
            }
        });
        BotEditarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEditarInfoActionPerformed(evt);
            }
        });
        getContentPane().add(BotEditarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 374, 556, 46));

        BotInicio1.setBorder(null);
        BotInicio1.setContentAreaFilled(false);
        BotInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicio1MouseEntered(evt);
            }
        });
        BotInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicio1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 190, 38));

        BotAdcLivro.setBorder(null);
        BotAdcLivro.setContentAreaFilled(false);
        BotAdcLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotAdcLivroMouseEntered(evt);
            }
        });
        BotAdcLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAdcLivroActionPerformed(evt);
            }
        });
        getContentPane().add(BotAdcLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 113, 556, 46));

        BotRmvLivro.setBorder(null);
        BotRmvLivro.setContentAreaFilled(false);
        BotRmvLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotRmvLivroMouseEntered(evt);
            }
        });
        BotRmvLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRmvLivroActionPerformed(evt);
            }
        });
        getContentPane().add(BotRmvLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 178, 556, 46));

        BotAdcExemplar.setBorder(null);
        BotAdcExemplar.setContentAreaFilled(false);
        BotAdcExemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotAdcExemplarMouseEntered(evt);
            }
        });
        BotAdcExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAdcExemplarActionPerformed(evt);
            }
        });
        getContentPane().add(BotAdcExemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 243, 556, 46));

        BotObterDados.setBorder(null);
        BotObterDados.setContentAreaFilled(false);
        BotObterDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotObterDadosMouseEntered(evt);
            }
        });
        BotObterDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotObterDadosActionPerformed(evt);
            }
        });
        getContentPane().add(BotObterDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 439, 556, 46));

        BotInicio2.setBorder(null);
        BotInicio2.setContentAreaFilled(false);
        BotInicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicio2MouseEntered(evt);
            }
        });
        BotInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicio2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 190, 38));

        BotInicio3.setBorder(null);
        BotInicio3.setContentAreaFilled(false);
        BotInicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicio3MouseEntered(evt);
            }
        });
        BotInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicio3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 568, 190, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaGerCatalogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotAdcLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAdcLivroMouseEntered
        // TODO add your handling code here:
        BotAdcLivro.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotAdcLivroMouseEntered

    private void BotAdcLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAdcLivroActionPerformed
        // TODO add your handling code here:
        new TelaAdcLivro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotAdcLivroActionPerformed

    private void BotRmvLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRmvLivroMouseEntered
        // TODO add your handling code here:
        BotRmvLivro.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotRmvLivroMouseEntered

    private void BotRmvLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRmvLivroActionPerformed
        // TODO add your handling code here:
        new TelaRmvLivro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotRmvLivroActionPerformed

    private void BotAdcExemplarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAdcExemplarMouseEntered
        // TODO add your handling code here:
        BotAdcExemplar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotAdcExemplarMouseEntered

    private void BotAdcExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAdcExemplarActionPerformed
        // TODO add your handling code here:
        new TelaAdcExemplar().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotAdcExemplarActionPerformed

    private void BotRmvExemplarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRmvExemplarMouseEntered
        // TODO add your handling code here:
        BotRmvExemplar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotRmvExemplarMouseEntered

    private void BotRmvExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRmvExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotRmvExemplarActionPerformed

    private void BotEditarInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEditarInfoMouseEntered
        // TODO add your handling code here:
        BotEditarInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotEditarInfoMouseEntered

    private void BotEditarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEditarInfoActionPerformed
        // TODO add your handling code here:
        new TelaEditarInfoLivro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotEditarInfoActionPerformed

    private void BotInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicioMouseEntered
        // TODO add your handling code here:
        BotInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicioMouseEntered

    private void BotInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicioActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicioActionPerformed

    private void BotObterDadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotObterDadosMouseEntered
        // TODO add your handling code here:
        BotObterDados.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_BotObterDadosMouseEntered

    private void BotObterDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotObterDadosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Quantidade de registros de cada entidade: \nTabela Usuarios: "+quant.obterTotalUsuarios()+"\nTabela Usuário Atual: " +quant.obterTotalUsuarioAtual()+"\nTabela Livros Biblioteca: "+quant.obterTotalLivros()+"\nTabela Exemplares: "+quant.obterTotalExemplares()+"\nTabela Empréstimos: "+quant.obterTotalEmprestimos());
    }//GEN-LAST:event_BotObterDadosActionPerformed

    private void BotInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicio1MouseEntered
        // TODO add your handling code here:
        BotInicio1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicio1MouseEntered

    private void BotInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicio1ActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicio1ActionPerformed

    private void BotInicio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicio2MouseEntered
        // TODO add your handling code here:
        BotInicio2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicio2MouseEntered

    private void BotInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicio2ActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicio2ActionPerformed

    private void BotInicio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicio3MouseEntered
        // TODO add your handling code here:
        BotInicio3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_BotInicio3MouseEntered

    private void BotInicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicio3ActionPerformed
        // TODO add your handling code here:
        new TelaCadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicio3ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAdcExemplar;
    private javax.swing.JButton BotAdcLivro;
    private javax.swing.JButton BotEditarInfo;
    private javax.swing.JButton BotInicio;
    private javax.swing.JButton BotInicio1;
    private javax.swing.JButton BotInicio2;
    private javax.swing.JButton BotInicio3;
    private javax.swing.JButton BotObterDados;
    private javax.swing.JButton BotRmvExemplar;
    private javax.swing.JButton BotRmvLivro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
