
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaRmvLivro extends javax.swing.JFrame {

    private UsuarioDAO livros = new UsuarioDAO();
    private String trecho;

    /**
     * Creates new form TelaRmvLivro
     */
    public TelaRmvLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        BotVoltar = new javax.swing.JButton();
        BotRmv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(93, 172, 156));
        jComboBox1.setBorder(null);
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 274, 490, 30));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<>(livros.obterNomeLivros())));

        BotVoltar.setBorder(null);
        BotVoltar.setContentAreaFilled(false);
        BotVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotVoltarMouseEntered(evt);
            }
        });
        BotVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 358, 92, 30));

        BotRmv.setBorder(null);
        BotRmv.setContentAreaFilled(false);
        BotRmv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotRmvMouseEntered(evt);
            }
        });
        BotRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRmvActionPerformed(evt);
            }
        });
        getContentPane().add(BotRmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 358, 92, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaRmvLivro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BotRmvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRmvMouseEntered
        // TODO add your handling code here:
        BotRmv.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotRmvMouseEntered

    private void BotVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotVoltarMouseEntered
        // TODO add your handling code here:
        BotVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotVoltarMouseEntered

    private void BotVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltarActionPerformed
        // TODO add your handling code here:
        new TelaGerCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotVoltarActionPerformed

    private void BotRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRmvActionPerformed
        // TODO add your handling code here:
        int inicio = ((String) jComboBox1.getSelectedItem()).indexOf(": ");
        int fim = ((String) jComboBox1.getSelectedItem()).indexOf(" -");

        if (inicio != -1 && fim != -1 && inicio < fim) {
            trecho = ((String) jComboBox1.getSelectedItem()).substring(inicio + 1, fim).trim();
            System.out.println("Trecho extraído: " + trecho);
        }
        Integer id = Integer.parseInt(trecho);
        livros.removerLivro(id);
        JOptionPane.showMessageDialog(null, "Livro removido!");
        new TelaGerCatalogo().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_BotRmvActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotRmv;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
