
import java.awt.Cursor;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {
    
    UsuarioDAO credenciais = new UsuarioDAO();
    private int id_logado=0;
    private RealizarLogin log;
    private int i;
    /**
     * Creates new form login
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Senha = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        BotExibirSenha = new javax.swing.JButton();
        OlhoFechado = new javax.swing.JLabel();
        OlhoAberto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Senha.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Senha.setForeground(new java.awt.Color(93, 172, 156));
        Senha.setBorder(null);
        Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SenhaMouseExited(evt);
            }
        });
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 306, 220, 20));
        Senha.setEchoChar('*');

        Email.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(93, 172, 156));
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 228, 248, 20));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 172, 156));
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 306, -1, 20));

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 172, 156));
        jLabel3.setText("E-mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 228, -1, 20));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 386, 115, 41));

        BotExibirSenha.setBorder(null);
        BotExibirSenha.setContentAreaFilled(false);
        BotExibirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotExibirSenhaMouseEntered(evt);
            }
        });
        BotExibirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExibirSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(BotExibirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 305, 18, 18));

        OlhoFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoFechado.png"))); // NOI18N
        getContentPane().add(OlhoFechado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 305, 20, 20));

        OlhoAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoAberto.png"))); // NOI18N
        getContentPane().add(OlhoAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 305, 20, 20));
        OlhoAberto.setVisible(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String senha = new String(Senha.getPassword());
            log = new RealizarLogin(Email.getText(), senha);
            id_logado = log.getId_logado();
            if(id_logado!= 0){
                JOptionPane.showMessageDialog(null, "Você será redirecionado para a tela inicial!");
                String nome = credenciais.obterNomePorId(id_logado);
                credenciais.removerUsuarioAntigo();
                credenciais.inserirUsuarioAtual(nome, Email.getText(), senha, credenciais.obterIsAdm(id_logado), id_logado);
                new TelaInicial().setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Email ou senha inválido!"); 
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void SenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenhaMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SenhaMouseEntered

    private void SenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenhaMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SenhaMouseExited

    private void BotExibirSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotExibirSenhaMouseEntered
        // TODO add your handling code here:
        BotExibirSenha.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotExibirSenhaMouseEntered

    private void BotExibirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExibirSenhaActionPerformed
        // TODO add your handling code here:
        if (i%2==0){
            OlhoFechado.setVisible(false);
            OlhoAberto.setVisible(true);
            Senha.setEchoChar((char)0);
        } else {
            OlhoFechado.setVisible(true);
            OlhoAberto.setVisible(false);
            Senha.setEchoChar('*');
        }
        i++;
    }//GEN-LAST:event_BotExibirSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotExibirSenha;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel OlhoAberto;
    private javax.swing.JLabel OlhoFechado;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
