
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.lang.Integer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaAdcLivro extends javax.swing.JFrame {

    UsuarioDAO adcLivro = new UsuarioDAO();
    CopiarImagem copiar = new CopiarImagem();

    /**
     * Creates new form TelaAdcLivro
     */
    public TelaAdcLivro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JTextField();
        Caminho = new javax.swing.JTextField();
        Sinopse = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        Autor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BotAdicionar = new javax.swing.JButton();
        BotVoltar = new javax.swing.JButton();
        NotaLivro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(93, 172, 156));
        Titulo.setBorder(null);
        Titulo.setOpaque(false);
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 250, 295, 20));

        Caminho.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Caminho.setForeground(new java.awt.Color(93, 172, 156));
        Caminho.setBorder(null);
        Caminho.setOpaque(false);
        getContentPane().add(Caminho, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 430, 602, 20));

        Sinopse.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Sinopse.setForeground(new java.awt.Color(93, 172, 156));
        Sinopse.setBorder(null);
        Sinopse.setOpaque(false);
        getContentPane().add(Sinopse, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 384, 602, 20));

        Genero.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Genero.setForeground(new java.awt.Color(93, 172, 156));
        Genero.setBorder(null);
        Genero.setOpaque(false);
        getContentPane().add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 336, 602, 20));

        Autor.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Autor.setForeground(new java.awt.Color(93, 172, 156));
        Autor.setBorder(null);
        Autor.setOpaque(false);
        getContentPane().add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 294, 602, 20));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 172, 156));
        jLabel2.setText("Obs.: O título, autores e gêneros do livo devem conter no máximo 31 caracteres contando os espaços, se ultrapassar, será cortado.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 610, -1));

        BotAdicionar.setBorder(null);
        BotAdicionar.setContentAreaFilled(false);
        BotAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotAdicionarMouseEntered(evt);
            }
        });
        BotAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(BotAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 116, 42));
        BotAdicionar.setOpaque(false);
        BotAdicionar.setContentAreaFilled(false);
        BotAdicionar.setBorderPainted(false);

        BotVoltar.setBorder(null);
        BotVoltar.setContentAreaFilled(false);
        BotVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotVoltarMouseEntered(evt);
            }
        });
        BotVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 520, 116, 42));
        BotAdicionar.setOpaque(false);
        BotAdicionar.setContentAreaFilled(false);
        BotAdicionar.setBorderPainted(false);

        NotaLivro.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        NotaLivro.setForeground(new java.awt.Color(93, 172, 156));
        NotaLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        NotaLivro.setToolTipText("");
        NotaLivro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NotaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaLivroActionPerformed(evt);
            }
        });
        getContentPane().add(NotaLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 246, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaAdcLivro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BotAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAdicionarMouseEntered
        // TODO add your handling code here:
        BotAdicionar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotAdicionarMouseEntered

    private void BotAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAdicionarActionPerformed
        // TODO add your handling code here:
        Integer selecionado;
        String mensagem;
        mensagem = adcLivro.inserirLivro(Titulo.getText(), Autor.getText(), Genero.getText(), Sinopse.getText(), selecionado = Integer.parseInt((String) NotaLivro.getSelectedItem()));
        if (mensagem.equalsIgnoreCase("Livro inserido com sucesso!")) {
            if (!Caminho.getText().equalsIgnoreCase("")) {
                copiar.CopiarImagem(Caminho.getText(), Titulo.getText());
            }
            JOptionPane.showMessageDialog(null, mensagem);
            setVisible(false);
            new TelaGerCatalogo().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, mensagem);
        }
    }//GEN-LAST:event_BotAdicionarActionPerformed

    private void BotVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotVoltarMouseEntered
        // TODO add your handling code here:
        BotVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotVoltarMouseEntered

    private void BotVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltarActionPerformed
        // TODO add your handling code here:
        new TelaGerCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotVoltarActionPerformed

    private void NotaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaLivroActionPerformed

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autor;
    private javax.swing.JButton BotAdicionar;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JTextField Caminho;
    private javax.swing.JTextField Genero;
    private javax.swing.JComboBox<String> NotaLivro;
    private javax.swing.JTextField Sinopse;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
