
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaRedefinicaoSucesso extends javax.swing.JFrame {
    UsuarioDAO verificarAdm = new UsuarioDAO();
    /**
     * Creates new form RedefinicaoSucesso
     */
    public TelaRedefinicaoSucesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botVoltar = new javax.swing.JButton();
        BotInicio = new javax.swing.JButton();
        BotCatalogo = new javax.swing.JButton();
        BotMinhaConta = new javax.swing.JButton();
        BotSair = new javax.swing.JButton();
        BotGerCatalogo = new javax.swing.JButton();
        ImgGerCatalogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botVoltar.setContentAreaFilled(false);
        botVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botVoltarMouseEntered(evt);
            }
        });
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 470, 102, 38));

        BotInicio.setBorder(null);
        BotInicio.setContentAreaFilled(false);
        BotInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicioMouseEntered(evt);
            }
        });
        BotInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 194, 40));

        BotCatalogo.setBorder(null);
        BotCatalogo.setContentAreaFilled(false);
        BotCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotCatalogoMouseEntered(evt);
            }
        });
        BotCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 194, 40));

        BotMinhaConta.setBorder(null);
        BotMinhaConta.setContentAreaFilled(false);
        BotMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotMinhaContaMouseEntered(evt);
            }
        });
        BotMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMinhaContaActionPerformed(evt);
            }
        });
        getContentPane().add(BotMinhaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 527, 194, 40));

        BotSair.setBorder(null);
        BotSair.setContentAreaFilled(false);
        BotSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotSairMouseEntered(evt);
            }
        });
        BotSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 568, 194, 30));

        BotGerCatalogo.setBorder(null);
        BotGerCatalogo.setContentAreaFilled(false);
        BotGerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotGerCatalogoMouseEntered(evt);
            }
        });
        BotGerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            BotGerCatalogo.setEnabled(true);
        } else {
            BotGerCatalogo.setEnabled(false);
        }

        ImgGerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/BotGerenciar.png"))); // NOI18N
        getContentPane().add(ImgGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            ImgGerCatalogo.setVisible(true);
        } else {
            ImgGerCatalogo.setVisible(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaRedefCredSucesso.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botVoltarActionPerformed

    private void botVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botVoltarMouseEntered

        // TODO add your handling code here:
        botVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botVoltarMouseEntered

    private void BotInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicioMouseEntered
        // TODO add your handling code here:
        BotInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicioMouseEntered

    private void BotInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicioActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicioActionPerformed

    private void BotCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotCatalogoMouseEntered
        // TODO add your handling code here:
        BotCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotCatalogoMouseEntered

    private void BotCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCatalogoActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotCatalogoActionPerformed

    private void BotMinhaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotMinhaContaMouseEntered
        // TODO add your handling code here:
        BotMinhaConta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotMinhaContaMouseEntered

    private void BotMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMinhaContaActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotMinhaContaActionPerformed

    private void BotSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSairMouseEntered
        // TODO add your handling code here:
        BotSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotSairMouseEntered

    private void BotSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSairActionPerformed
        // TODO add your handling code here:
        new TelaCadastro().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_BotSairActionPerformed

    private void BotGerCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotGerCatalogoMouseEntered
        // TODO add your handling code here:
        BotGerCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotGerCatalogoMouseEntered

    private void BotGerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerCatalogoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerCatalogo().setVisible(true);
    }//GEN-LAST:event_BotGerCatalogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotCatalogo;
    private javax.swing.JButton BotGerCatalogo;
    private javax.swing.JButton BotInicio;
    private javax.swing.JButton BotMinhaConta;
    private javax.swing.JButton BotSair;
    private javax.swing.JLabel ImgGerCatalogo;
    private javax.swing.JButton botVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
