
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author João
 */
public class TelaInfoLivro extends javax.swing.JFrame {
    private String titulo, autor, genero, sinopse;
    private int id_livro, id;
    private UsuarioDAO livro = new UsuarioDAO();
    /**
     * Creates new form TelaInfoLivro
     */
    public TelaInfoLivro(int id) {
        initComponents();
        this.id = id;
        verInfo(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotEmprestimo = new javax.swing.JButton();
        botVoltar = new javax.swing.JButton();
        Estrela = new javax.swing.JLabel();
        Nota = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        NomeAutor = new javax.swing.JLabel();
        NomeLivro = new javax.swing.JLabel();
        GeneroLivro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SinopseLivro = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotEmprestimo.setContentAreaFilled(false);
        BotEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotEmprestimoMouseEntered(evt);
            }
        });
        BotEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(BotEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 506, 116, 40));

        botVoltar.setContentAreaFilled(false);
        botVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botVoltarMouseEntered(evt);
            }
        });
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 506, 116, 40));

        Estrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrela.png"))); // NOI18N
        getContentPane().add(Estrela, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 138, 22, 20));

        Nota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nota.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 138, 20, 20));

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ID.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 135, 50, 20));

        NomeAutor.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        NomeAutor.setForeground(new java.awt.Color(93, 172, 156));
        NomeAutor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(NomeAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 185, 610, 20));

        NomeLivro.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        NomeLivro.setForeground(new java.awt.Color(255, 255, 255));
        NomeLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 139, 627, 25));

        GeneroLivro.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        GeneroLivro.setForeground(new java.awt.Color(93, 172, 156));
        GeneroLivro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(GeneroLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 228, 610, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Constantia", 0, 11)); // NOI18N

        SinopseLivro.setColumns(20);
        SinopseLivro.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        SinopseLivro.setRows(5);
        SinopseLivro.setBorder(null);
        jScrollPane1.setViewportView(SinopseLivro);
        SinopseLivro.setForeground(new java.awt.Color(93, 172, 156));
        SinopseLivro.setLineWrap(true);
        SinopseLivro.setWrapStyleWord(true);
        SinopseLivro.setEditable(false);
        SinopseLivro.setOpaque(false);
        SinopseLivro.setBorder(null);

        // Adiciona o JTextArea ao JScrollPane
        jScrollPane1.setViewportView(SinopseLivro);
        jScrollPane1.setBounds(94, 270, 612, 216);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 270, 612, 214));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/InfoLivro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEmprestimoMouseEntered
        // TODO add your handling code here:
        BotEmprestimo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotEmprestimoMouseEntered

    private void BotEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEmprestimoActionPerformed
        // TODO add your handling code here:
        new TelaRealizarEmp(this.id).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotEmprestimoActionPerformed

    private void botVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botVoltarMouseEntered
        // TODO add your handling code here:
        botVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botVoltarMouseEntered

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botVoltarActionPerformed

    public void verInfo(int id){
        titulo = livro.obterNomeLivro(id);
        autor = livro.obterAutorLivro(id);
        genero = livro.obterGeneroLivro(id);
        sinopse = livro.obterSinopseLivro(id);
        id_livro = id;
        
        NomeLivro.setText(titulo);
        NomeAutor.setText(autor);
        GeneroLivro.setText(genero);
        SinopseLivro.setText(sinopse);
        ID.setText("ID: "+ id_livro);
        Nota.setText(""+ livro.obterNotaLivro(id));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotEmprestimo;
    private javax.swing.JLabel Estrela;
    private javax.swing.JLabel GeneroLivro;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel NomeAutor;
    private javax.swing.JLabel NomeLivro;
    private javax.swing.JLabel Nota;
    private javax.swing.JTextArea SinopseLivro;
    private javax.swing.JButton botVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
