
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaInicial extends javax.swing.JFrame {
    UsuarioDAO verificarAdm = new UsuarioDAO();
    UsuarioDAO livros = new UsuarioDAO();
    ArrayList<Integer> ids_livro = new ArrayList<Integer>();
    int i=0;
    /**
     * Creates new form TelaIncial
     */
    public TelaInicial() {
        initComponents();
        atualizarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_minhaconta = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        botao_catalogo = new javax.swing.JButton();
        BotGerCatalogo = new javax.swing.JButton();
        ImgGerCatalogo = new javax.swing.JLabel();
        BotLivro1 = new javax.swing.JButton();
        BotLivro2 = new javax.swing.JButton();
        BotLivro3 = new javax.swing.JButton();
        NomeL1 = new javax.swing.JLabel();
        NomeL2 = new javax.swing.JLabel();
        NomeL3 = new javax.swing.JLabel();
        livro1 = new javax.swing.JLabel();
        livro2 = new javax.swing.JLabel();
        livro3 = new javax.swing.JLabel();
        Estrelas5L1 = new javax.swing.JLabel();
        Estrelas4L1 = new javax.swing.JLabel();
        Estrelas3L1 = new javax.swing.JLabel();
        Estrelas2L1 = new javax.swing.JLabel();
        Estrelas1L1 = new javax.swing.JLabel();
        Estrelas0L1 = new javax.swing.JLabel();
        AutorL1 = new javax.swing.JLabel();
        GeneroL1 = new javax.swing.JLabel();
        Estrelas5L2 = new javax.swing.JLabel();
        Estrelas4L2 = new javax.swing.JLabel();
        Estrelas3L2 = new javax.swing.JLabel();
        Estrelas2L2 = new javax.swing.JLabel();
        Estrelas1L2 = new javax.swing.JLabel();
        Estrelas0L2 = new javax.swing.JLabel();
        AutorL2 = new javax.swing.JLabel();
        GeneroL2 = new javax.swing.JLabel();
        Estrelas5L3 = new javax.swing.JLabel();
        Estrelas4L3 = new javax.swing.JLabel();
        Estrelas3L3 = new javax.swing.JLabel();
        Estrelas2L3 = new javax.swing.JLabel();
        Estrelas1L3 = new javax.swing.JLabel();
        Estrelas0L3 = new javax.swing.JLabel();
        AutorL3 = new javax.swing.JLabel();
        GeneroL3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_minhaconta.setBorder(null);
        botao_minhaconta.setContentAreaFilled(false);
        botao_minhaconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_minhacontaMouseEntered(evt);
            }
        });
        botao_minhaconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_minhacontaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_minhaconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 192, 35));

        botao_sair.setBorder(null);
        botao_sair.setContentAreaFilled(false);
        botao_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_sairMouseEntered(evt);
            }
        });
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 190, 30));

        botao_catalogo.setBorder(null);
        botao_catalogo.setContentAreaFilled(false);
        botao_catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_catalogoMouseEntered(evt);
            }
        });
        botao_catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_catalogoActionPerformed(evt);
            }
        });
        getContentPane().add(botao_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 190, 38));

        BotGerCatalogo.setBorder(null);
        BotGerCatalogo.setContentAreaFilled(false);
        BotGerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotGerCatalogoMouseEntered(evt);
            }
        });
        BotGerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            BotGerCatalogo.setEnabled(true);
        } else {
            BotGerCatalogo.setEnabled(false);
        }

        ImgGerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/BotGerenciar.png"))); // NOI18N
        getContentPane().add(ImgGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            ImgGerCatalogo.setVisible(true);
        } else {
            ImgGerCatalogo.setVisible(false);
        }

        BotLivro1.setBorder(null);
        BotLivro1.setContentAreaFilled(false);
        BotLivro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro1MouseEntered(evt);
            }
        });
        BotLivro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 110, 83, 125));

        BotLivro2.setBorder(null);
        BotLivro2.setContentAreaFilled(false);
        BotLivro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro2MouseEntered(evt);
            }
        });
        BotLivro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 83, 125));

        BotLivro3.setBorder(null);
        BotLivro3.setContentAreaFilled(false);
        BotLivro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotLivro3MouseEntered(evt);
            }
        });
        BotLivro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLivro3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotLivro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 110, 83, 125));

        NomeL1.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL1.setForeground(new java.awt.Color(45, 123, 109));
        NomeL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 258, 184, 20));
        if(1+i<=ids_livro.size()){
            NomeL1.setText(livros.obterNomeLivro(ids_livro.get(1+i-1)));
        }

        NomeL2.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL2.setForeground(new java.awt.Color(45, 123, 109));
        NomeL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 258, 184, 20));
        if(2+i<=ids_livro.size()){
            NomeL2.setText(livros.obterNomeLivro(ids_livro.get(2+i-1)));
        }

        NomeL3.setFont(new java.awt.Font("Constantia", 0, 13)); // NOI18N
        NomeL3.setForeground(new java.awt.Color(45, 123, 109));
        NomeL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(NomeL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 258, 184, 20));
        if(3+i<=ids_livro.size()){
            NomeL3.setText(livros.obterNomeLivro(ids_livro.get(3+i-1)));
        }
        getContentPane().add(livro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 110, 83, 125));
        if (!NomeL1.getText().equalsIgnoreCase("")){
            livro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL1.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 83, 125));
        if (!NomeL2.getText().equalsIgnoreCase("")){
            livro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL2.getText()+".jpg"))); // NOI18N
        }
        getContentPane().add(livro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 110, 83, 125));
        if (!NomeL3.getText().equalsIgnoreCase("")){
            livro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/"+NomeL3.getText()+".jpg"))); // NOI18N
        }

        Estrelas5L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas5L1.setVisible(false);

        Estrelas4L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas4L1.setVisible(false);

        Estrelas3L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas3L1.setVisible(false);

        Estrelas2L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas2L1.setVisible(false);

        Estrelas1L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas1L1.setVisible(false);

        Estrelas0L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 83, 18));
        Estrelas0L1.setVisible(false);

        AutorL1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL1.setForeground(new java.awt.Color(93, 172, 156));
        AutorL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 273, 184, 20));
        if(1+i<=ids_livro.size()){
            AutorL1.setText(livros.obterAutorLivro(ids_livro.get(1+i-1)));
        }

        GeneroL1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL1.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 288, 184, 20));
        if(1+i<=ids_livro.size()){
            GeneroL1.setText(livros.obterGeneroLivro(ids_livro.get(1+i-1)));
        }

        Estrelas5L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas5L2.setVisible(false);

        Estrelas4L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas4L2.setVisible(false);

        Estrelas3L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas3L2.setVisible(false);

        Estrelas2L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas2L2.setVisible(false);

        Estrelas1L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas1L2.setVisible(false);

        Estrelas0L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 83, 18));
        Estrelas0L2.setVisible(false);

        AutorL2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL2.setForeground(new java.awt.Color(93, 172, 156));
        AutorL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 273, 184, 20));
        if(2+i<=ids_livro.size()){
            AutorL2.setText(livros.obterAutorLivro(ids_livro.get(2+i-1)));
        }

        GeneroL2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL2.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 288, 184, 20));
        if(2+i<=ids_livro.size()){
            GeneroL2.setText(livros.obterGeneroLivro(ids_livro.get(2+i-1)));
        }

        Estrelas5L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas5.png"))); // NOI18N
        getContentPane().add(Estrelas5L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas5L3.setVisible(false);

        Estrelas4L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas4.png"))); // NOI18N
        getContentPane().add(Estrelas4L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas4L3.setVisible(false);

        Estrelas3L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas3.png"))); // NOI18N
        getContentPane().add(Estrelas3L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas3L3.setVisible(false);

        Estrelas2L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas2.png"))); // NOI18N
        getContentPane().add(Estrelas2L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas2L3.setVisible(false);

        Estrelas1L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas1.png"))); // NOI18N
        getContentPane().add(Estrelas1L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas1L3.setVisible(false);

        Estrelas0L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/Estrelas.png"))); // NOI18N
        getContentPane().add(Estrelas0L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 240, 83, 18));
        Estrelas0L3.setVisible(false);

        AutorL3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        AutorL3.setForeground(new java.awt.Color(93, 172, 156));
        AutorL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AutorL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 273, 184, 20));
        if(3+i<=ids_livro.size()){
            AutorL3.setText(livros.obterAutorLivro(ids_livro.get(3+i-1)));
        }

        GeneroL3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        GeneroL3.setForeground(new java.awt.Color(93, 172, 156));
        GeneroL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(GeneroL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 288, 184, 20));
        if(3+i<=ids_livro.size()){
            GeneroL3.setText(livros.obterGeneroLivro(ids_livro.get(3+i-1)));
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaInicial.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarCatalogo(){
        ids_livro = livros.obterIdLivrosInicial();
        if (1 + i <= ids_livro.size()) {
            ids_livro = (livros.obterIdLivrosInicial());
            NomeL1.setText(livros.obterNomeLivro(ids_livro.get(1 + i - 1)));
            livro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL1.getText() + ".jpg")));
            AutorL1.setText(livros.obterAutorLivro(ids_livro.get(1 + i - 1)));
            GeneroL1.setText(livros.obterGeneroLivro(ids_livro.get(1 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(1 + i - 1));
            Estrelas0L1.setVisible(nota == 0);
            Estrelas1L1.setVisible(nota == 1);
            Estrelas2L1.setVisible(nota == 2);
            Estrelas3L1.setVisible(nota == 3);
            Estrelas4L1.setVisible(nota == 4);
            Estrelas5L1.setVisible(nota == 5);
            BotLivro1.setEnabled(true);
        } else {
            Estrelas0L1.setVisible(false); 
            Estrelas1L1.setVisible(false); 
            Estrelas2L1.setVisible(false);
            Estrelas3L1.setVisible(false); 
            Estrelas4L1.setVisible(false); 
            Estrelas5L1.setVisible(false);
            NomeL1.setText("");
            livro1.setIcon(null);
            AutorL1.setText("");
            GeneroL1.setText("");
            BotLivro1.setEnabled(false);
        }

        if (2 + i <= ids_livro.size()) {
            NomeL2.setText(livros.obterNomeLivro(ids_livro.get(2 + i - 1)));
            livro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL2.getText() + ".jpg")));
            AutorL2.setText(livros.obterAutorLivro(ids_livro.get(2 + i - 1)));
            GeneroL2.setText(livros.obterGeneroLivro(ids_livro.get(2 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(2 + i - 1));
            Estrelas0L2.setVisible(nota == 0);
            Estrelas1L2.setVisible(nota == 1);
            Estrelas2L2.setVisible(nota == 2);
            Estrelas3L2.setVisible(nota == 3);
            Estrelas4L2.setVisible(nota == 4);
            Estrelas5L2.setVisible(nota == 5);
            BotLivro2.setEnabled(true);
        } else {
            Estrelas0L2.setVisible(false); 
            Estrelas1L2.setVisible(false); 
            Estrelas2L2.setVisible(false);
            Estrelas3L2.setVisible(false); 
            Estrelas4L2.setVisible(false); 
            Estrelas5L2.setVisible(false);
            NomeL2.setText("");
            livro2.setIcon(null);
            AutorL2.setText("");
            GeneroL2.setText("");
            BotLivro2.setEnabled(false);
        }

        if (3 + i <= ids_livro.size()) {
            NomeL3.setText(livros.obterNomeLivro(ids_livro.get(3 + i - 1)));
            livro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaLivros/" + NomeL3.getText() + ".jpg")));
            AutorL3.setText(livros.obterAutorLivro(ids_livro.get(3 + i - 1)));
            GeneroL3.setText(livros.obterGeneroLivro(ids_livro.get(3 + i - 1)));
            int nota = livros.obterNotaLivro(ids_livro.get(3 + i - 1));
            Estrelas0L3.setVisible(nota == 0);
            Estrelas1L3.setVisible(nota == 1);
            Estrelas2L3.setVisible(nota == 2);
            Estrelas3L3.setVisible(nota == 3);
            Estrelas4L3.setVisible(nota == 4);
            Estrelas5L3.setVisible(nota == 5);
            BotLivro3.setEnabled(true);
        } else {
            NomeL3.setText("");
            livro3.setIcon(null);
            AutorL3.setText("");
            GeneroL3.setText("");
            BotLivro3.setEnabled(false);
        }
    }
    
    private void botao_minhacontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_minhacontaActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_minhacontaActionPerformed

    private void botao_minhacontaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_minhacontaMouseEntered
        // TODO add your handling code here:
        botao_minhaconta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_minhacontaMouseEntered

    private void botao_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sairMouseEntered
        // TODO add your handling code here:
        botao_sair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_sairMouseEntered

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Você está saindo!");
        new TelaCadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_catalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_catalogoMouseEntered
        // TODO add your handling code here:
        botao_catalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_catalogoMouseEntered

    private void botao_catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_catalogoActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_catalogoActionPerformed

    private void BotGerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerCatalogoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerCatalogo().setVisible(true);
    }//GEN-LAST:event_BotGerCatalogoActionPerformed

    private void BotGerCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotGerCatalogoMouseEntered
        // TODO add your handling code here:
        BotGerCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotGerCatalogoMouseEntered

    private void BotLivro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro1MouseEntered
        BotLivro1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro1MouseEntered

    private void BotLivro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro1ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(1 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro1ActionPerformed

    private void BotLivro2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro2MouseEntered
        // TODO add your handling code here:
        BotLivro2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro2MouseEntered

    private void BotLivro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro2ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(2 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro2ActionPerformed

    private void BotLivro3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLivro3MouseEntered
        // TODO add your handling code here:
        BotLivro3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotLivro3MouseEntered

    private void BotLivro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLivro3ActionPerformed
        // TODO add your handling code here:
        new TelaInfoLivro(ids_livro.get(3 + i - 1)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotLivro3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorL1;
    private javax.swing.JLabel AutorL2;
    private javax.swing.JLabel AutorL3;
    private javax.swing.JButton BotGerCatalogo;
    private javax.swing.JButton BotLivro1;
    private javax.swing.JButton BotLivro2;
    private javax.swing.JButton BotLivro3;
    private javax.swing.JLabel Estrelas0L1;
    private javax.swing.JLabel Estrelas0L2;
    private javax.swing.JLabel Estrelas0L3;
    private javax.swing.JLabel Estrelas1L1;
    private javax.swing.JLabel Estrelas1L2;
    private javax.swing.JLabel Estrelas1L3;
    private javax.swing.JLabel Estrelas2L1;
    private javax.swing.JLabel Estrelas2L2;
    private javax.swing.JLabel Estrelas2L3;
    private javax.swing.JLabel Estrelas3L1;
    private javax.swing.JLabel Estrelas3L2;
    private javax.swing.JLabel Estrelas3L3;
    private javax.swing.JLabel Estrelas4L1;
    private javax.swing.JLabel Estrelas4L2;
    private javax.swing.JLabel Estrelas4L3;
    private javax.swing.JLabel Estrelas5L1;
    private javax.swing.JLabel Estrelas5L2;
    private javax.swing.JLabel Estrelas5L3;
    private javax.swing.JLabel GeneroL1;
    private javax.swing.JLabel GeneroL2;
    private javax.swing.JLabel GeneroL3;
    private javax.swing.JLabel ImgGerCatalogo;
    private javax.swing.JLabel NomeL1;
    private javax.swing.JLabel NomeL2;
    private javax.swing.JLabel NomeL3;
    private javax.swing.JButton botao_catalogo;
    private javax.swing.JButton botao_minhaconta;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel livro1;
    private javax.swing.JLabel livro2;
    private javax.swing.JLabel livro3;
    // End of variables declaration//GEN-END:variables
}
