
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aluno
 */
public class TelaRedefCred extends javax.swing.JFrame {
    UsuarioDAO credenciais = new UsuarioDAO();
    UsuarioDAO verificarAdm = new UsuarioDAO();
    int i;
    /**
     * Creates new form RedefinirCredenciais
     */
    public TelaRedefCred() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotSair = new javax.swing.JButton();
        BotRedefinir = new javax.swing.JButton();
        BotInicio = new javax.swing.JButton();
        BotMinhaConta = new javax.swing.JButton();
        BotCatalogo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        BotExibirSenha = new javax.swing.JButton();
        OlhoFechado = new javax.swing.JLabel();
        OlhoAberto = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        BotGerCatalogo = new javax.swing.JButton();
        ImgGerCatalogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotSair.setBorder(null);
        BotSair.setContentAreaFilled(false);
        BotSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotSairMouseEntered(evt);
            }
        });
        BotSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 568, 194, 30));

        BotRedefinir.setBorder(null);
        BotRedefinir.setContentAreaFilled(false);
        BotRedefinir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotRedefinirMouseEntered(evt);
            }
        });
        BotRedefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRedefinirActionPerformed(evt);
            }
        });
        getContentPane().add(BotRedefinir, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 459, 116, 40));

        BotInicio.setBorder(null);
        BotInicio.setContentAreaFilled(false);
        BotInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicioMouseEntered(evt);
            }
        });
        BotInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 194, 40));

        BotMinhaConta.setBorder(null);
        BotMinhaConta.setContentAreaFilled(false);
        BotMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotMinhaContaMouseEntered(evt);
            }
        });
        BotMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotMinhaContaActionPerformed(evt);
            }
        });
        getContentPane().add(BotMinhaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 527, 194, 40));

        BotCatalogo.setBorder(null);
        BotCatalogo.setContentAreaFilled(false);
        BotCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotCatalogoMouseEntered(evt);
            }
        });
        BotCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 194, 40));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 172, 156));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 395, -1, 20));

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 172, 156));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 237, -1, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 172, 156));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 316, -1, 20));

        Email.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(93, 172, 156));
        Email.setBorder(null);
        Email.setOpaque(false);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 316, 290, 20));

        Nome.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(93, 172, 156));
        Nome.setBorder(null);
        Nome.setOpaque(false);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 237, 290, 20));

        BotExibirSenha.setBorder(null);
        BotExibirSenha.setContentAreaFilled(false);
        BotExibirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotExibirSenhaMouseEntered(evt);
            }
        });
        BotExibirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExibirSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(BotExibirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 392, 18, 18));

        OlhoFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoFechado.png"))); // NOI18N
        getContentPane().add(OlhoFechado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 392, 18, 18));

        OlhoAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoAberto.png"))); // NOI18N
        getContentPane().add(OlhoAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 392, 18, 18));
        OlhoAberto.setVisible(false);

        Senha.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Senha.setForeground(new java.awt.Color(93, 172, 156));
        Senha.setBorder(null);
        Senha.setOpaque(false);
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 395, 260, 20));
        Senha.setEchoChar('*');

        BotGerCatalogo.setBorder(null);
        BotGerCatalogo.setContentAreaFilled(false);
        BotGerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotGerCatalogoMouseEntered(evt);
            }
        });
        BotGerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            BotGerCatalogo.setEnabled(true);
        } else {
            BotGerCatalogo.setEnabled(false);
        }

        ImgGerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/BotGerenciar.png"))); // NOI18N
        getContentPane().add(ImgGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            ImgGerCatalogo.setVisible(true);
        } else {
            ImgGerCatalogo.setVisible(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaRedefCred.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSairMouseEntered
        // TODO add your handling code here:
        BotSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotSairMouseEntered

    private void BotSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSairActionPerformed
        // TODO add your handling code here:
        new TelaCadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotSairActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void BotRedefinirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRedefinirMouseEntered
        // TODO add your handling code here:
        BotRedefinir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotRedefinirMouseEntered

    private void BotRedefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRedefinirActionPerformed
        // TODO add your handling code here:
        int id;
        boolean is_adm;
        id = credenciais.obterIDAtual();
        is_adm = credenciais.obterIs_AdmAtual();
        String senha = new String (Senha.getPassword());
        credenciais.removerCredAntiga(id);
        credenciais.inserirUsuario(id, Nome.getText(), senha, Email.getText(), is_adm);
        credenciais.AtualizarUsuarioAtual(id, Nome.getText(), Email.getText(), senha, is_adm);
        new TelaRedefinicaoSucesso().setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_BotRedefinirActionPerformed

    private void BotInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicioMouseEntered
        // TODO add your handling code here:
        BotInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicioMouseEntered

    private void BotInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicioActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicioActionPerformed

    private void BotMinhaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotMinhaContaMouseEntered
        // TODO add your handling code here:
        BotMinhaConta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotMinhaContaMouseEntered

    private void BotMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotMinhaContaActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotMinhaContaActionPerformed

    private void BotCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotCatalogoMouseEntered
        // TODO add your handling code here:
        BotCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_BotCatalogoMouseEntered

    private void BotCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCatalogoActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotCatalogoActionPerformed

    private void BotExibirSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotExibirSenhaMouseEntered
        // TODO add your handling code here:
        BotExibirSenha.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotExibirSenhaMouseEntered

    private void BotExibirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExibirSenhaActionPerformed
        // TODO add your handling code here:
        if (i%2==0){
            OlhoFechado.setVisible(false);
            OlhoAberto.setVisible(true);
            Senha.setEchoChar((char)0);
        } else {
            OlhoFechado.setVisible(true);
            OlhoAberto.setVisible(false);
            Senha.setEchoChar('*');
        }
        i++;
    }//GEN-LAST:event_BotExibirSenhaActionPerformed

    private void BotGerCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotGerCatalogoMouseEntered
        // TODO add your handling code here:
        BotGerCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotGerCatalogoMouseEntered

    private void BotGerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerCatalogoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerCatalogo().setVisible(true);
    }//GEN-LAST:event_BotGerCatalogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotCatalogo;
    private javax.swing.JButton BotExibirSenha;
    private javax.swing.JButton BotGerCatalogo;
    private javax.swing.JButton BotInicio;
    private javax.swing.JButton BotMinhaConta;
    private javax.swing.JButton BotRedefinir;
    private javax.swing.JButton BotSair;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel ImgGerCatalogo;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel OlhoAberto;
    private javax.swing.JLabel OlhoFechado;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
