
import java.awt.Cursor;
import java.util.Vector;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaRmvExemplar extends javax.swing.JFrame {

    private UsuarioDAO livros = new UsuarioDAO();
    private String trecho;
    private Integer id;

    /**
     * Creates new form TelaRmvExemplar
     */
    public TelaRmvExemplar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LivroSelecionado = new javax.swing.JComboBox<>();
        ExemplarSelecionado = new javax.swing.JComboBox<>();
        BotVoltar = new javax.swing.JButton();
        BotRmv = new javax.swing.JButton();
        BotConf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LivroSelecionado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LivroSelecionado.setForeground(new java.awt.Color(93, 172, 156));
        LivroSelecionado.setBorder(null);
        LivroSelecionado.setOpaque(false);
        LivroSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivroSelecionadoActionPerformed(evt);
            }
        });
        getContentPane().add(LivroSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 229, 490, 20));
        LivroSelecionado.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<>(livros.obterNomeLivros())));

        ExemplarSelecionado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExemplarSelecionado.setForeground(new java.awt.Color(93, 172, 156));
        ExemplarSelecionado.setBorder(null);
        ExemplarSelecionado.setOpaque(false);
        ExemplarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemplarSelecionadoActionPerformed(evt);
            }
        });
        getContentPane().add(ExemplarSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 265, 490, 20));

        BotVoltar.setBorder(null);
        BotVoltar.setContentAreaFilled(false);
        BotVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotVoltarMouseEntered(evt);
            }
        });
        BotVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 420, 115, 40));

        BotRmv.setBorder(null);
        BotRmv.setContentAreaFilled(false);
        BotRmv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotRmvMouseEntered(evt);
            }
        });
        BotRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRmvActionPerformed(evt);
            }
        });
        getContentPane().add(BotRmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 420, 115, 40));

        BotConf.setBorder(null);
        BotConf.setContentAreaFilled(false);
        BotConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotConfMouseEntered(evt);
            }
        });
        BotConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotConfActionPerformed(evt);
            }
        });
        getContentPane().add(BotConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 420, 115, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaRmvExemplar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarExemplar() {
        ExemplarSelecionado.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<>(livros.obterIdExemplares(id))));
    }
    private void BotVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotVoltarMouseEntered
        // TODO add your handling code here:
        BotVoltar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotVoltarMouseEntered

    private void BotVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltarActionPerformed
        // TODO add your handling code here:
        new TelaGerCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotVoltarActionPerformed

    private void BotRmvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotRmvMouseEntered
        // TODO add your handling code here:
        BotRmv.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotRmvMouseEntered

    private void BotRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRmvActionPerformed
        // TODO add your handling code here:
        int inicio = ((String) LivroSelecionado.getSelectedItem()).indexOf(": ");
        int fim = ((String) LivroSelecionado.getSelectedItem()).indexOf(" -");

        if (inicio != -1 && fim != -1 && inicio < fim) {
            trecho = ((String) LivroSelecionado.getSelectedItem()).substring(inicio + 1, fim).trim();
            System.out.println("Trecho extraído: " + trecho);
        }
        id = Integer.parseInt(trecho);
        livros.removerExemplar(id);
    }//GEN-LAST:event_BotRmvActionPerformed

    private void BotConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotConfMouseEntered
        // TODO add your handling code here:
        BotConf.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotConfMouseEntered

    private void BotConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotConfActionPerformed
        // TODO add your handling code here:
        int inicio = ((String) LivroSelecionado.getSelectedItem()).indexOf(": ");
        int fim = ((String) LivroSelecionado.getSelectedItem()).indexOf(" -");

        if (inicio != -1 && fim != -1 && inicio < fim) {
            trecho = ((String) LivroSelecionado.getSelectedItem()).substring(inicio + 1, fim).trim();
            System.out.println("Trecho extraído: " + trecho);
        }
        id = Integer.parseInt(trecho);
        atualizarExemplar();
    }//GEN-LAST:event_BotConfActionPerformed

    private void LivroSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivroSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LivroSelecionadoActionPerformed

    private void ExemplarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemplarSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExemplarSelecionadoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotConf;
    private javax.swing.JButton BotRmv;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JComboBox<String> ExemplarSelecionado;
    private javax.swing.JComboBox<String> LivroSelecionado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
