
import java.awt.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaCadastro extends javax.swing.JFrame {

    private Cadastro cad = new Cadastro();
    private int i;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotExibirSenha = new javax.swing.JButton();
        Senha = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OlhoFechado = new javax.swing.JLabel();
        OlhoAberto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotExibirSenha.setBorder(null);
        BotExibirSenha.setContentAreaFilled(false);
        BotExibirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotExibirSenhaMouseEntered(evt);
            }
        });
        BotExibirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExibirSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(BotExibirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 349, 18, 18));

        Senha.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Senha.setForeground(new java.awt.Color(93, 172, 156));
        Senha.setBorder(null);
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 350, 210, -1));
        Senha.setEchoChar('*');

        Email.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(93, 172, 156));
        Email.setBorder(null);
        Email.setOpaque(false);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 271, 240, 20));

        Nome.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(93, 172, 156));
        Nome.setBorder(null);
        Nome.setOpaque(false);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 191, 240, 20));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 346, 116, 42));
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 172, 156));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 444, 116, 42));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 172, 156));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 191, -1, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 172, 156));
        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 271, -1, -1));

        OlhoFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoFechado.png"))); // NOI18N
        getContentPane().add(OlhoFechado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 347, 20, 20));

        OlhoAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/OlhoAberto.png"))); // NOI18N
        getContentPane().add(OlhoAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 347, 20, 20));
        OlhoAberto.setVisible(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaCadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Você será redirecionado para a tela de Login!");
        setVisible(false);
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String senha = new String(Senha.getPassword());
        boolean realizado = cad.Cadastro(Nome.getText(), senha, Email.getText());
        if (realizado){
            JOptionPane.showMessageDialog(null, "Cadastro realizado!!");
            new TelaLogin().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "O email cadastrado já está em uso!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void BotExibirSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotExibirSenhaMouseEntered
        // TODO add your handling code here:
        BotExibirSenha.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotExibirSenhaMouseEntered

    private void BotExibirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExibirSenhaActionPerformed
        // TODO add your handling code here:
        if (i%2==0){
            OlhoFechado.setVisible(false);
            OlhoAberto.setVisible(true);
            Senha.setEchoChar((char)0);
        } else {
            OlhoFechado.setVisible(true);
            OlhoAberto.setVisible(false);
            Senha.setEchoChar('*');
        }
        i++;
        
    }//GEN-LAST:event_BotExibirSenhaActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotExibirSenha;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel OlhoAberto;
    private javax.swing.JLabel OlhoFechado;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
