
import java.awt.Cursor;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author João
 */
public class TelaMinhaConta extends javax.swing.JFrame {
    UsuarioDAO credenciais = new UsuarioDAO();
    UsuarioDAO verificarAdm = new UsuarioDAO();
    
    /**
     * Creates new form TelaMinhaConta
     */
    public TelaMinhaConta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotCredenciais = new javax.swing.JButton();
        botao_catalogo = new javax.swing.JButton();
        botao_minhaconta = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        BotInicio = new javax.swing.JButton();
        BotHistEmp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotGerCatalogo = new javax.swing.JButton();
        ImgGerCatalogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotCredenciais.setBorder(null);
        BotCredenciais.setContentAreaFilled(false);
        BotCredenciais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotCredenciaisMouseEntered(evt);
            }
        });
        BotCredenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCredenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(BotCredenciais, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 236, 556, 46));

        botao_catalogo.setBorder(null);
        botao_catalogo.setContentAreaFilled(false);
        botao_catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_catalogoMouseEntered(evt);
            }
        });
        botao_catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_catalogoActionPerformed(evt);
            }
        });
        getContentPane().add(botao_catalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 190, 38));

        botao_minhaconta.setBorder(null);
        botao_minhaconta.setContentAreaFilled(false);
        botao_minhaconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_minhacontaMouseEntered(evt);
            }
        });
        botao_minhaconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_minhacontaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_minhaconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 192, 35));

        botao_sair.setBorder(null);
        botao_sair.setContentAreaFilled(false);
        botao_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_sairMouseEntered(evt);
            }
        });
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 190, 30));

        BotInicio.setBorder(null);
        BotInicio.setContentAreaFilled(false);
        BotInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotInicioMouseEntered(evt);
            }
        });
        BotInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, 190, 38));

        BotHistEmp.setBorder(null);
        BotHistEmp.setContentAreaFilled(false);
        BotHistEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotHistEmpMouseEntered(evt);
            }
        });
        BotHistEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotHistEmpActionPerformed(evt);
            }
        });
        getContentPane().add(BotHistEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 170, 556, 46));

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 234));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 78, 470, 30));
        String email = credenciais.obterEmailAtual();
        jLabel3.setText(email);

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 234));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 48, 470, 40));
        String nome = credenciais.obterNomeAtual();
        jLabel2.setText(nome);

        BotGerCatalogo.setBorder(null);
        BotGerCatalogo.setContentAreaFilled(false);
        BotGerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotGerCatalogoMouseEntered(evt);
            }
        });
        BotGerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BotGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            BotGerCatalogo.setEnabled(true);
        } else {
            BotGerCatalogo.setEnabled(false);
        }

        ImgGerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/BotGerenciar.png"))); // NOI18N
        getContentPane().add(ImgGerCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 192, 40));
        if (verificarAdm.obterIs_AdmAtual()==true){
            ImgGerCatalogo.setVisible(true);
        } else {
            ImgGerCatalogo.setVisible(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagemTelas/TelaMinhaConta.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotCredenciaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotCredenciaisMouseEntered
        // TODO add your handling code here:
        BotCredenciais.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotCredenciaisMouseEntered

    private void BotCredenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCredenciaisActionPerformed
        // TODO add your handling code here:
        new TelaRedefCred().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotCredenciaisActionPerformed

    private void botao_catalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_catalogoMouseEntered
        // TODO add your handling code here:
        botao_catalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_catalogoMouseEntered

    private void botao_catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_catalogoActionPerformed
        // TODO add your handling code here:
        new TelaCatalogo().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_catalogoActionPerformed

    private void botao_minhacontaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_minhacontaMouseEntered
        // TODO add your handling code here:
        botao_minhaconta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_minhacontaMouseEntered

    private void botao_minhacontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_minhacontaActionPerformed
        // TODO add your handling code here:
        new TelaMinhaConta().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_minhacontaActionPerformed

    private void botao_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sairMouseEntered
        // TODO add your handling code here:
        botao_sair.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botao_sairMouseEntered

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Você está saindo!");
        new TelaCadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botao_sairActionPerformed

    private void BotInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotInicioMouseEntered
        // TODO add your handling code here:
        BotInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotInicioMouseEntered

    private void BotInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInicioActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BotInicioActionPerformed

    private void BotHistEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotHistEmpMouseEntered
        // TODO add your handling code here:
        BotHistEmp.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_BotHistEmpMouseEntered

    private void BotHistEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotHistEmpActionPerformed
        // TODO add your handling code here:
        new TelaHistEmp().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_BotHistEmpActionPerformed

    private void BotGerCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotGerCatalogoMouseEntered
        // TODO add your handling code here:
        BotGerCatalogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotGerCatalogoMouseEntered

    private void BotGerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerCatalogoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerCatalogo().setVisible(true);
    }//GEN-LAST:event_BotGerCatalogoActionPerformed

    /*public void InserirCredenciais(String nome, String email){
        jLabel2.setText(nome);
        jLabel3.setText(email);
                
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotCredenciais;
    private javax.swing.JButton BotGerCatalogo;
    private javax.swing.JButton BotHistEmp;
    private javax.swing.JButton BotInicio;
    private javax.swing.JLabel ImgGerCatalogo;
    private javax.swing.JButton botao_catalogo;
    private javax.swing.JButton botao_minhaconta;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
